# Generated by Django 5.1 on 2024-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('admin', 'administrateur'), ('user', 'utilisateur'), ('super_admin', 'super administrateur')], default='user'),
        ),
    ]
