# Generated by Django 5.1 on 2024-09-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_person_is_active_person_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='doh'),
        ),
    ]
