# Generated by Django 5.1 on 2024-09-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_remove_person_is_active_remove_person_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(unique=True),
        ),
    ]
